services:
  - type: web
    name: TestHive
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      php artisan config:cache && \
      php artisan migrate --force && \
      php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
