services:
  - type: web
    name: TestHive
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      ls -la database/migrations && \
      php artisan config:cache && \
      php artisan migrate:fresh --seed && \
      php artisan serve --host=0.0.0.0 --port=10000
